version: '2.1'
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman:
    executor: newman/postman-newman-docker
    environment:
      HOST: https://zjs-cms.herokuapp.com
    steps:
      - checkout
      - newman/newman-run:
          collection: ./ZJS-CMS.postman_collection.json
          timeout: '5000'
          additional-options: --env-var "HOST=${HOST}"
workflows:
  newman_api:
    jobs:
      - newman